version: '3'
services:
  user_service:
    restart: always
    build:
      context: ./
      dockerfile: build/Dockerfile
    image: user_service:latest
    links:
      - db:db
    ports:
      - "8080:8080"
    environment:
      PG_HOST: "db"
      PG_PORT: 5432
    depends_on:
      - "db"
      - "migrate"
    command: [ "/app/user_service" ]

  migrate:
    build:
      context: ./
      dockerfile: build/migration/Dockerfile
    image: migrate:latest
    links:
      - db:db
    volumes:
      - ./migrations/:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: goose -v postgres postgres://user_service:user_service@db:5432/user_service up

  db:
    image: postgres:14.5
#    volumes:
#      - /opt/docker_data/user_service/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user_service
      - POSTGRES_PASSWORD=user_service
      - POSTGRES_DB=user_service
    ports:
      - 55437:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 10
