version: '3'
services:
  user_service:
    restart: always
    build:
      context: ../.
      dockerfile: ./build/Dockerfile
    image: user_service:latest
    links:
      - db:db
    ports:
      - 8080:8080
    depends_on:
      - "db"
      - "migrator"
    command: [ "/app/wait-for-it.sh", "db:5432", "--", "/app/user_service" ]

  migrator:
    build:
      context: ../.
      dockerfile: build/migration/Dockerfile
    image: migrate:latest
    links:
      - db:db
    depends_on:
      - "db"
    command: [ "/app/wait-for-it.sh", "db:5432", "--", "goose -v postgres postgres://user_service:user_service@localhost:55437/user_service migrate" ]

  db:
    image: postgres:14.5
#    volumes:
#      - /opt/docker_data/user_service/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user_service
      - POSTGRES_PASSWORD=user_service
      - POSTGRES_DB=user_service
    ports:
      - 55437:5432
